import { clear } from "console";

export const translations = {
    en: {
        error: "Error",
        searchUsers: "Search users...",
        permissionManagement: "Permission Management",
        permissions: "Permissions",
        clear: "Clear",
        loading: "Loading...",
        lotCost: "Lot Cost",
        storageLock: "Storage Lock",
        dashboard: "Dashboard",
        welcome: "Welcome back! Here's what's happening with your inventory.",
        totalProducts: "Total Products",
        todaysSales: "Today's Sales",
        totalProfit: "Total Profit",
        lowStock: "Low Stock Items",
        requiresAttention: "Requires attention",
        salesTrend: "Sales Trend",
        profitTrend: "Profit Trend",
        recentActivity: "Recent Activity",
        // Products
        productManagement: "Product Management",
        manageProducts: "Manage your inventory products and stock levels.",
        addProduct: "Add Product",
        addNewProduct: "Add New Product",
        editProduct: "Edit Product",
        deleteProduct: "Delete Product",
        sellProduct: "Sell Product",
        cancel: "Cancel",
        saveChanges: "Save Changes",
        // Locks
        storageLocks: "Storage Locks",
        manageLocks: "Manage storage locations and capacity.",
        addLock: "Add Storage Lock",
        addNewLock: "Add New Storage Lock",
        editLock: "Edit Storage Lock",
        deleteLock: "Delete Storage Lock",
        lockName: "Lock Name",
        capacity: "Capacity",
        location: "Location",
        // Categories
        categories: "Categories",
        organizeCategories: "Organize your products into categories.",
        addCategory: "Add Category",
        addNewCategory: "Add New Category",
        editCategory: "Edit Category",
        deleteCategory: "Delete Category",
        categoryName: "Category Name",
        description: "Description",
        products: "Products",
        created: "Created",
        actions: "Actions",
        // Sell
        sell: "Sell",
        quantity: "Quantity",
        unitPrice: "Unit Price",
        total: "Total",
        profit: "Profit",
        transactions: "Transactions",
        salesCompletedToday: "Sales completed today",
        // Users
        userManagement: "User Management",
        manageUsers: "Manage users and their permissions.",
        addUser: "Add User",
        addNewUser: "Add New User",
        editUser: "Edit User",
        deleteUser: "Delete User",
        user: "User",
        email: "Email",
        role: "Role",
        status: "Status",
        lastLogin: "Last Login",
        password: "Password",
        // Reports
        reports: "Reports & Analytics",
        trackPerformance: "Track performance and generate insights.",
        exportCSV: "Export CSV",
        exportPDF: "Export PDF",
        reportFilters: "Report Filters",
        dateRange: "Date Range",
        reportType: "Report Type",
        startDate: "Start Date",
        endDate: "End Date",
        totalSales: "Total Sales",
        inventoryValue: "Inventory Value",
        avgOrderValue: "Avg. Order Value",
        salesByCategory: "Category",
        keyMetrics: "Key Metrics",
        bestSellingProduct: "Best Selling Product",
        topCategory: "Top Category",
        avgProfitMargin: "Average Profit Margin",
        totalTransactions: "Total Transactions",
        lowStockItems: "Low Stock Items",
        returnRate: "Return Rate",
        // Common
        update: "Update",
        create: "Create",
        save: "Save",
        search: "Search",
        select: "Select",
        manageInventory: "Manage your inventory products and stock levels.",
        searchProducts: "Search products...",
        product: "Product",
        barcode: "Barcode",
        category: "Category",
        lock: "Storage Lock",
        productName: "Product Name",
        enterProductName: "Enter product name",
        enterBarcode: "Enter barcode",
        scanOrEnterBarcode: "Scan or enter barcode",
        selectCategory: "Select category",
        selectStorageLock: "Select storage lock",
        productImage: "Product Image",
        clickToUpload: "Click or drag to upload",
        imageFormats: "Supported formats: JPG, PNG, GIF",
        uploadingImage: "Uploading image...",
        productAdded: "Product added successfully",
        errorAddingProduct: "Error adding product",
        invalidQuantity: "Invalid quantity",
        available: "Available",
        quantityToSell: "Quantity to Sell",
        max: "Max",
        productInformation: "Product Information",
        categoryStorage: "Category & Storage",
        stockPricing: "Stock & Pricing",
        confirmDelete: "Are you sure you want to delete",
        delete: "Delete",
        customer: "Customer",
        time: "Time",
        searchStorageLocks: "Search storage locks...",
        totalLocks: "Total Locks",
        storageLocations: "Storage locations",
        totalCapacity: "Total Capacity",
        maximumItems: "Maximum items",
        currentStock: "Current Stock",
        itemsStored: "Items stored",
        utilization: "Utilization",
        storageLockUpdated: "Storage lock updated",
        storageLockCreated: "Storage lock created",
        storageLockUpdatedDesc: "The storage lock has been updated successfully.",
        storageLockCreatedDesc: "New storage lock has been created successfully.",
        failedToUpdateStorageLock: "Failed to update storage lock.",
        failedToCreateStorageLock: "Failed to create storage lock.",
        enterLockName: "Enter lock name (e.g., Lock A1)",
        enterMaxCapacity: "Enter maximum capacity",
        enterStorageLocation: "Enter storage location",
        // User-specific translations
        userDeleted: "User deleted",
        userDeletedDesc: "The user has been successfully deleted.",
        failedToDeleteUser: "Failed to delete user.",
        failedToFetchUsers: "Failed to fetch users.",
        userUpdated: "User updated",
        userCreated: "User created",
        userUpdatedDesc: "The user has been successfully updated.",
        userCreatedDesc: "New user has been created successfully.",
        failedToUpdateUser: "Failed to update user.",
        failedToCreateUser: "Failed to create user.",
        selectRole: "Select role",
        selectStatus: "Select status",
        admin: "Admin",
        staff: "Staff",
        viewer: "Viewer",
        active: "Active",
        inactive: "Inactive",
        fullName: "Full Name",
        enterFullName: "Enter full name",
        enterEmail: "Enter email address",
        enterPassword: "Enter password",
        module: "Module",
        configurePermissions: "Configure permissions for different user roles. Changes will apply to all users with the selected role.",
        savePermissions: "Save Permissions",
        fromLastPeriod: "from last period",
        profitMargin: "profit margin",
        currentStockValue: "Current stock value",
        salesProfitTrend: "Sales & Profit Trend",
        inventoryValueTrend: "Inventory Value Trend",
        salesReport: "Sales Report",
        profitAnalysis: "Profit Analysis",
        inventoryReport: "Inventory Report",
        categoryPerformance: "Category Performance",
        last7Days: "Last 7 Days",
        last30Days: "Last 30 Days",
        last3Months: "Last 3 Months",
        last6Months: "Last 6 Months",
        lastYear: "Last Year",
        customRange: "Custom Range",
        sales: "Sales",
        management: "Management",
        settings: "Settings",
        settingsLabel: "You can manage your settings here.",
        lowStockAlert: "Low Stock Alert",
        lowStockAlertDesc: "Get notified when products are running low",
        notifications: "Notifications",
        notificationsDesc: "Manage your notification preferences",
        resetData: "Reset Data",
        resetDataDesc: "Reset all application data (irreversible action)",
        lowStockThreshold: "Low Stock Threshold",
        enableLowStockAlerts: "Enable Low Stock Alerts",
        enableEmailNotifications: "Enable Email Notifications",
        enablePushNotifications: "Enable Push Notifications",
        resetAllData: "Reset All Data",
        confirmReset: "Are you sure you want to reset all data? This action cannot be undone.",
        dataResetSuccess: "Data has been reset successfully",
        settingsUpdated: "Settings updated successfully",
        lowStockThresholdDesc: "Alert when stock falls below {threshold}",
        noProductsFound: "No products found. Let's create one!",
        addStock: "Add Stock",
        notHaveCategory: "No categories found. You can create one!",
        welcomeLoginTitle: "You are logged in",
        welcomeLoginMessage: "Welcome back! You are logged in at {time}",
        markAllAsRead: "Mark all as read",
        noNotifications: "No notifications",
        viewAllNotifications: "View all notifications",
        allNotifications: "All Notifications",
        markAsRead: "Mark as read",
        remove: "Remove",
        allCaughtUp: "You're all caught up!",
        // Additional UI translations
        fastory: "Fastory",
        home: "Home",
        logout: "Logout",
        profile: "Profile",
        account: "Account",
        language: "Language",
        theme: "Theme",
        dark: "Dark",
        light: "Light",
        system: "System",
        yes: "Yes",
        no: "No",
        // Login page translations
        signIn: "Sign In",
        signInWithGoogle: "Sign in with Google",
        pleaseWait: "Please wait...",
        orContinueWith: "Or continue with",
        fillAllFields: "Please fill in all fields.",
        invalidCredentials: "Invalid email or password. Please try again.",
        enterYourEmail: "Enter your email",
        enterYourPassword: "Enter your password",
        signingOut: "Signing out...",
        // Chatbot translations
        chatbotWelcome: "Hello! I'm your inventory assistant. How can I help you today?",
        chatbotError: "I'm sorry, I'm having trouble responding right now. Please try again later.",
        typeYourMessage: "Type your message...",
        chat: "Chat",
        // Confirmation dialogs
        confirmDeleteCategory: "Are you sure you want to delete this category?",
        confirmDeleteUser: "Are you sure you want to delete this user?",
        confirmDeleteStorageLock: "Are you sure you want to delete this storage lock?",
        // Error messages
        failedToFetchRoles: "Failed to fetch roles.",
        failedToFetchUserData: "Failed to fetch user data.",
        failedToDeleteStorageLock: "Failed to delete storage lock.",
        failedToLoadPermissions: "Failed to load permissions.",
        saveFailed: "Failed to save permissions.",
        failedToUpdateProfile: "Failed to update profile. Please try again.",
        failedToFindProduct: "Failed to find product",
        failedToCompleteSale: "Failed to complete sale",
        failedToFetchNotifications: "Failed to fetch notifications",
        failedToSendNotification: "Failed to send notification",
        failedToDeleteNotification: "Failed to delete notification",
        failedToSellProduct: "Failed to sell product",
        failedToEditProduct: "Failed to edit product",
        failedToFetchSales: "Failed to fetch sales.",
        failedToLookupProduct: "Failed to lookup product.",
        // Profile and Settings
        profilePersonalization: "Profile Personalization",
        customizeProfile: "Customize your profile information and appearance",
        changePhoto: "Change Photo",
        firstName: "First Name",
        lastName: "Last Name",
        enterFirstName: "Enter your first name",
        enterLastName: "Enter your last name",
        emailReadOnly: "Email (read-only)",
        customizeProfileInfo: "Customize your profile information and appearance",
        profilePicture: "Profile picture",
        updateProfile: "Update Profile",
        updating: "Updating...",
        profileUpdated: "Profile updated",
        profileUpdatedDesc: "Your profile has been updated successfully.",
        imageSelected: "Image selected",
        dontForgetSave: "Don't forget to save your changes!",
        // New notification translations
        manageNotifications: "Manage user notifications and announcements",
        sendNotification: "Send Notification",
        createAndSend: "Create and send notifications to selected users",
        notificationTitle: "Notification title",
        actionUrlOptional: "Action URL (Optional)",
        notificationMessage: "Notification message",
        templates: "Templates (Click to use)",
        selectUsers: "Select Users",
        selected: "selected",
        sendToUsers: "Send to",
        sending: "Sending...",
        userNotifications: "User Notifications",
        viewManageNotifications: "View and manage notifications for each user",
        view: "View",
        notificationsFor: "Notifications for",
        noNotificationsFound: "No notifications found",
        new: "New",
        action: "Action",
        validationError: "Validation Error",
        fillAllRequiredFields: "Please fill in all required fields and select at least one user",
        notificationSent: "Notification sent to",
        users: "user(s)",
        failedToSend: "Failed to send notification",
        notificationDeleted: "Notification deleted successfully",
        totalUsers: "Total Users",
        totalNotifications: "Total Notifications",
        unread: "Unread",
        read: "Read",
        all: "All",
        none: "None",
        title: "Title",
        type: "Type",
        message: "Message",
        info: "Info",
        warning: "Warning",
        success: "Success",
        failedToFetch: "Failed to fetch users",
        // Barcode Dialog - new unique keys
        addProductsToInventory: "Add Products to Inventory",
        scanProductsToSell: "Scan Products to Sell",
        barcodeInputLabel: "Scan or Enter Barcode",
        barcodeInputPlaceholder: "Scan or enter barcode",
        productNotFound: "Product Not Found",
        pleaseCheckBarcode: "Please check the barcode.",
        emptyCart: "Empty cart",
        pleaseAddItemsToCart: "Please add items to cart first",
        productsToAdd: "Products to Add",
        itemsToSell: "Items to Sell",
        itemsCount: "items",
        totalAmount: "Total",
        onlyQuantityAvailable: "Only",
        quantityAvailable: "available",
        addToInventory: "Add to Inventory",
        confirmSale: "Confirm Sale",
        yourPreferencesSaved: "Your preferences have been saved successfully.",
        // Reports page enhancements
        monthlyPerformance: "Monthly Performance",
        salesProgress: "Sales Progress",
        salesTarget: "Sales Target",
        profitTarget: "Profit Target",
        customerSatisfaction: "Customer Satisfaction",
        revenueTrend: "Chart Analysis",
        revenue: "Revenue",
        netProfit: "Net Profit",
        salesForecast: "Sales Forecast",
        profitForecast: "Profit Forecast",
        loadingChart: "Loading Chart...",
        loadingCategories: "Loading Categories...",
        loadingTrend: "Loading Trend...",
        noSalesData: "No sales data available for the selected period",
        noCategoryData: "No category data available",
        noCategoryContribution: "No category contribution data",
        noStorageLockData: "No storage lock data",
        noRevenueTrendData: "No revenue trend data available",
        salesVsCapital: "Sales vs Inventory Capital",
        lowStockCoverage: "Low Stock Coverage",
        categoryDistribution: "Category Distribution",
        over: "Over",
        more: "more",
        // ...add more as needed
    },
    th: {
        fromLastPeriod: "จากช่วงเวลาก่อนหน้า",
        profitMargin: "อัตรากำไร",
        currentStockValue: "มูลค่าสินค้าคงคลังปัจจุบัน",
        salesProfitTrend: "แนวโน้มยอดขายและกำไร",
        inventoryValueTrend: "แนวโน้มมูลค่าสินค้าคงคลัง",
        salesByCategory: "หมวดหมู่",
        keyMetrics: "ตัวชี้วัดสำคัญ",
        bestSellingProduct: "สินค้าขายดี",
        topCategory: "หมวดหมู่ยอดนิยม",
        avgProfitMargin: "อัตรากำไรเฉลี่ย",
        totalTransactions: "ธุรกรรมทั้งหมด",
        lowStockItems: "สินค้าใกล้หมด",
        returnRate: "อัตราการคืนสินค้า",
        error: "ข้อผิดพลาด",
        searchUsers: "ค้นหาผู้ใช้...",
        permissionManagement: "การจัดการสิทธิ์",
        permissions: "สิทธิ์การเข้าถึง",
        searchStorageLocks: "ค้นหาที่เก็บสินค้า...",
        totalLocks: "จำนวนที่เก็บสินค้าทั้งหมด",
        storageLocations: "ตำแหน่งที่เก็บสินค้า",
        totalCapacity: "ความจุรวม",
        maximumItems: "จำนวนสูงสุด",
        currentStock: "สต็อกปัจจุบัน",
        itemsStored: "จำนวนที่จัดเก็บ",
        utilization: "การใช้งาน",
        storageLockUpdated: "อัปเดตที่เก็บสินค้าแล้ว",
        storageLockCreated: "สร้างที่เก็บสินค้าแล้ว",
        storageLockUpdatedDesc: "อัปเดตที่เก็บสินค้าสำเร็จ",
        storageLockCreatedDesc: "สร้างที่เก็บสินค้าใหม่สำเร็จ",
        failedToUpdateStorageLock: "อัปเดตที่เก็บสินค้าไม่สำเร็จ",
        failedToCreateStorageLock: "สร้างที่เก็บสินค้าไม่สำเร็จ",
        enterLockName: "กรอกชื่อที่เก็บ (เช่น Lock A1)",
        enterMaxCapacity: "กรอกความจุสูงสุด",
        enterStorageLocation: "กรอกตำแหน่งที่เก็บสินค้า",
        clear: "ล้าง",
        time: "เวลา",
        customer: "ลูกค้า",
        loading: "กำลังโหลด...",
        lotCost: "ต้นทุนล็อต",
        storageLock: "ล็อคที่เก็บสินค้า",
        dashboard: "แดชบอร์ด",
        welcome: "ยินดีต้อนรับ! นี่คือภาพรวมสินค้าคงคลังของคุณ",
        totalProducts: "สินค้าทั้งหมด",
        todaysSales: "ยอดขายวันนี้",
        totalProfit: "กำไรรวม",
        lowStock: "สินค้าใกล้หมด",
        requiresAttention: "ต้องการตรวจสอบ",
        salesTrend: "แนวโน้มยอดขาย",
        profitTrend: "แนวโน้มกำไร",
        recentActivity: "กิจกรรมล่าสุด",
        // Products
        productManagement: "จัดการสินค้า",
        manageProducts: "จัดการสินค้าและสต็อกของคุณ",
        addProduct: "เพิ่มสินค้า",
        addNewProduct: "เพิ่มสินค้าใหม่",
        editProduct: "แก้ไขสินค้า",
        deleteProduct: "ลบสินค้า",
        sellProduct: "ขายสินค้า",
        cancel: "ยกเลิก",
        saveChanges: "บันทึกการเปลี่ยนแปลง",
        // Locks
        storageLocks: "ที่เก็บสินค้า",
        manageLocks: "จัดการที่เก็บสินค้าและความจุ",
        addLock: "เพิ่มที่เก็บสินค้า",
        addNewLock: "เพิ่มที่เก็บสินค้าใหม่",
        editLock: "แก้ไขที่เก็บสินค้า",
        deleteLock: "ลบที่เก็บสินค้า",
        lockName: "ชื่อที่เก็บ",
        capacity: "ความจุ",
        location: "ตำแหน่ง",
        // Categories
        categories: "หมวดหมู่",
        organizeCategories: "จัดหมวดหมู่สินค้า",
        addCategory: "เพิ่มหมวดหมู่",
        addNewCategory: "เพิ่มหมวดหมู่ใหม่",
        editCategory: "แก้ไขหมวดหมู่",
        deleteCategory: "ลบหมวดหมู่",
        categoryName: "ชื่อหมวดหมู่",
        description: "รายละเอียด",
        products: "สินค้า",
        created: "สร้างเมื่อ",
        actions: "การกระทำ",
        // Sell
        sell: "ขาย",
        quantity: "จำนวน",
        unitPrice: "ราคาต่อหน่วย",
        total: "รวม",
        profit: "กำไร",
        transactions: "ธุรกรรม",
        salesCompletedToday: "ขายสำเร็จวันนี้",
        // Users
        userManagement: "จัดการผู้ใช้",
        manageUsers: "จัดการผู้ใช้และสิทธิ์การเข้าถึง",
        addUser: "เพิ่มผู้ใช้",
        addNewUser: "เพิ่มผู้ใช้ใหม่",
        editUser: "แก้ไขผู้ใช้",
        deleteUser: "ลบผู้ใช้",
        user: "ผู้ใช้",
        email: "อีเมล",
        role: "บทบาท",
        status: "สถานะ",
        lastLogin: "เข้าสู่ระบบล่าสุด",
        password: "รหัสผ่าน",
        // Reports
        reports: "รายงานและวิเคราะห์",
        trackPerformance: "ติดตามผลและวิเคราะห์ข้อมูล",
        exportCSV: "ส่งออก CSV",
        exportPDF: "ส่งออก PDF",
        reportFilters: "ตัวกรองรายงาน",
        dateRange: "ช่วงวันที่",
        reportType: "ประเภทรายงาน",
        startDate: "วันที่เริ่มต้น",
        endDate: "วันที่สิ้นสุด",
        totalSales: "ยอดขายรวม",
        inventoryValue: "มูลค่าสินค้าคงคลัง",
        avgOrderValue: "มูลค่าคำสั่งซื้อเฉลี่ย",
        // Common
        update: "อัปเดต",
        create: "สร้าง",
        save: "บันทึก",
        search: "ค้นหา",
        select: "เลือก",
        // Add these for product page and dialogs:
        manageInventory: "จัดการสินค้าและสต็อกของคุณ",
        searchProducts: "ค้นหาสินค้า...",
        product: "สินค้า",
        barcode: "บาร์โค้ด",
        category: "หมวดหมู่",
        lock: "ที่เก็บสินค้า",
        productName: "ชื่อสินค้า",
        enterProductName: "กรอกชื่อสินค้า",
        enterBarcode: "กรอกบาร์โค้ด",
        scanOrEnterBarcode: "สแกนหรือกรอกบาร์โค้ด",
        selectCategory: "เลือกหมวดหมู่",
        selectStorageLock: "เลือกที่เก็บสินค้า",
        productImage: "รูปสินค้า",
        clickToUpload: "คลิกหรือวางไฟล์เพื่ออัปโหลด",
        imageFormats: "รองรับไฟล์: JPG, PNG, GIF",
        uploadingImage: "กำลังอัปโหลดรูปภาพ...",
        productAdded: "เพิ่มสินค้าสำเร็จ",
        errorAddingProduct: "เกิดข้อผิดพลาดในการเพิ่มสินค้า",
        invalidQuantity: "จำนวนไม่ถูกต้อง",
        available: "คงเหลือ",
        quantityToSell: "จำนวนที่ต้องการขาย",
        max: "สูงสุด",
        productInformation: "ข้อมูลสินค้า",
        categoryStorage: "หมวดหมู่และที่เก็บ",
        stockPricing: "สต็อกและราคา",
        confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบ",
        delete: "ลบ",
        // User-specific translations
        userDeleted: "ลบผู้ใช้แล้ว",
        userDeletedDesc: "ลบผู้ใช้สำเร็จ",
        failedToDeleteUser: "ลบผู้ใช้ไม่สำเร็จ",
        failedToFetchUsers: "ดึงข้อมูลผู้ใช้ไม่สำเร็จ",
        userUpdated: "อัปเดตผู้ใช้แล้ว",
        userCreated: "สร้างผู้ใช้แล้ว",
        userUpdatedDesc: "อัปเดตผู้ใช้สำเร็จ",
        userCreatedDesc: "สร้างผู้ใช้ใหม่สำเร็จ",
        failedToUpdateUser: "อัปเดตผู้ใช้ไม่สำเร็จ",
        failedToCreateUser: "สร้างผู้ใช้ไม่สำเร็จ",
        selectRole: "เลือกบทบาท",
        selectStatus: "เลือกสถานะ",
        admin: "ผู้ดูแล",
        staff: "พนักงาน",
        viewer: "ผู้ชม",
        active: "ใช้งาน",
        inactive: "ไม่ใช้งาน",
        fullName: "ชื่อ-นามสกุล",
        enterFullName: "กรอกชื่อ-นามสกุล",
        enterEmail: "กรอกอีเมล",
        enterPassword: "กรอกรหัสผ่าน",
        module: "โมดูล",
        configurePermissions: "กำหนดสิทธิ์สำหรับบทบาทผู้ใช้แต่ละประเภท การเปลี่ยนแปลงจะมีผลกับผู้ใช้ทุกคนในบทบาทที่เลือก",
        savePermissions: "บันทึกสิทธิ์",
        read: "อ่าน",
        last7Days: "7 วันที่ผ่านมา",
        last30Days: "30 วันที่ผ่านมา",
        last3Months: "3 เดือนที่ผ่านมา",
        last6Months: "6 เดือนที่ผ่านมา",
        lastYear: "ปีที่ผ่านมา",
        customRange: "กำหนดช่วงเอง",
        salesReport: "รายงานยอดขาย",
        profitAnalysis: "วิเคราะห์กำไร",
        inventoryReport: "รายงานสินค้าคงคลัง",
        categoryPerformance: "ประสิทธิภาพหมวดหมู่",
        sales: "ยอดขาย",
        management: "การจัดการ",
        settings: "การตั้งค่า",
        settingsLabel: "คุณสามารถจัดการการตั้งค่าของคุณที่นี่",
        lowStockAlert: "สินค้าใกล้หมด",
        lowStockAlertDesc: "รับการแจ้งเตือนเมื่อสินค้าใกล้หมด",
        notifications: "แจ้งเตือน",
        notificationsDesc: "จัดการการแจ้งเตือนของคุณ",
        resetData: "รีเซ็ทข้อมูล",
        resetDataDesc: "รีเซ็ทข้อมูลทั้งหมด (ไม่สามารถกู้คืนได้)",
        lowStockThreshold: "จำนวนขั้นต่ำสำหรับแจ้งเตือน",
        enableLowStockAlerts: "เปิดการแจ้งเตือนสินค้าใกล้หมด",
        enableEmailNotifications: "เปิดการแจ้งเตือนทางอีเมล",
        enablePushNotifications: "เปิดการแจ้งเตือนแบบ Push",
        resetAllData: "รีเซ็ทข้อมูลทั้งหมด",
        confirmReset: "คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ทข้อมูลทั้งหมด? การกระทำนี้ไม่สามารถยกเลิกได้",
        dataResetSuccess: "รีเซ็ทข้อมูลสำเร็จแล้ว",
        settingsUpdated: "อัปเดตการตั้งค่าสำเร็จ",
        lowStockThresholdDesc: "แจ้งเตือนเมื่อสินค้าต่ำกว่า {threshold}",
        noProductsFound: "ไม่พบสินค้า มาสร้างสินค้าแรกกันเถอะ!",
        addStock: "เพิ่มสต็อก",
        notHaveCategory: "ไม่พบหมวดหมู่ คุณสามารถสร้างหมวดหมู่ใหม่ได้!",
        welcomeLoginTitle: "คุณได้เข้าสู่ระบบแล้ว",
        welcomeLoginMessage: "ยินดีต้อนรับ! คุณเข้าสู่ระบบเมื่อ {time}",
        markAllAsRead: "ทำเครื่องหมายทั้งหมดว่าอ่านแล้ว",
        noNotifications: "ไม่มีการแจ้งเตือน",
        viewAllNotifications: "ดูการแจ้งเตือนทั้งหมด",
        allNotifications: "การแจ้งเตือนทั้งหมด",
        markAsRead: "ทำเครื่องหมายว่าอ่านแล้ว",
        remove: "ลบ",
        allCaughtUp: "คุณอ่านข่าวสารครบทุกข้อความแล้ว!",
        // Additional UI translations
        fastory: "แฟสตอรี่",
        home: "หน้าแรก",
        logout: "ออกจากระบบ",
        profile: "โปรไฟล์",
        account: "บัญชี",
        language: "ภาษา",
        theme: "ธีม",
        dark: "มืด",
        light: "สว่าง",
        system: "ระบบ",
        yes: "ใช่",
        no: "ไม่",
        // Login page translations
        signIn: "เข้าสู่ระบบ",
        signInWithGoogle: "เข้าสู่ระบบด้วย Google",
        pleaseWait: "กรุณารอสักครู่...",
        orContinueWith: "หรือดำเนินการต่อด้วย",
        fillAllFields: "กรุณากรอกข้อมูลให้ครบถ้วน",
        invalidCredentials: "อีเมลหรือรหัสผ่านไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง",
        enterYourEmail: "กรุณากรอกอีเมล",
        enterYourPassword: "กรุณากรอกรหัสผ่าน",
        signingOut: "กำลังออกจากระบบ...",
        // Chatbot translations
        chatbotWelcome: "สวัสดีครับ! ผมเป็นผู้ช่วยระบบคลังสินค้า ผมสามารถช่วยอะไรคุณได้บ้างครับ?",
        chatbotError: "ขออภัยครับ ตอนนี้ผมมีปัญหาในการตอบสนอง กรุณาลองใหม่อีกครั้งครับ",
        typeYourMessage: "พิมพ์ข้อความของคุณ...",
        chat: "แชท",
        // Confirmation dialogs
        confirmDeleteCategory: "คุณแน่ใจหรือไม่ว่าต้องการลบหมวดหมู่นี้?",
        confirmDeleteUser: "คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้คนนี้?",
        confirmDeleteStorageLock: "คุณแน่ใจหรือไม่ว่าต้องการลบที่เก็บสินค้านี้?",
        // Error messages
        failedToFetchRoles: "ไม่สามารถดึงข้อมูลบทบาทได้",
        failedToFetchUserData: "ไม่สามารถดึงข้อมูลผู้ใช้ได้",
        failedToDeleteStorageLock: "ไม่สามารถลบที่เก็บสินค้าได้",
        failedToLoadPermissions: "ไม่สามารถโหลดสิทธิ์การเข้าถึงได้",
        saveFailed: "ไม่สามารถบันทึกสิทธิ์การเข้าถึงได้",
        failedToUpdateProfile: "ไม่สามารถอัปเดตโปรไฟล์ได้ กรุณาลองใหม่อีกครั้ง",
        failedToFindProduct: "ไม่สามารถค้นหาสินค้าได้",
        failedToCompleteSale: "ไม่สามารถทำรายการขายให้สำเร็จได้",
        failedToFetchNotifications: "ไม่สามารถดึงข้อมูลการแจ้งเตือนได้",
        failedToSendNotification: "ไม่สามารถส่งการแจ้งเตือนได้",
        failedToDeleteNotification: "ไม่สามารถลบการแจ้งเตือนได้",
        failedToSellProduct: "ไม่สามารถขายสินค้าได้",
        failedToEditProduct: "ไม่สามารถแก้ไขสินค้าได้",
        failedToFetchSales: "ไม่สามารถดึงข้อมูลการขายได้",
        failedToLookupProduct: "ไม่สามารถค้นหาสินค้าได้",
        // Profile and Settings
        profilePersonalization: "การปรับแต่งโปรไฟล์",
        customizeProfile: "ปรับแต่งข้อมูลและรูปลักษณ์ของคุณ",
        changePhoto: "เปลี่ยนรูปภาพ",
        firstName: "ชื่อจริง",
        lastName: "นามสกุล",
        enterFirstName: "กรอกชื่อจริง",
        enterLastName: "กรอกนามสกุล",
        emailReadOnly: "อีเมล (อ่านอย่างเดียว)",
        customizeProfileInfo: "ปรับแต่งข้อมูลส่วนตัวและรูปลักษณ์ของคุณ",
        profilePicture: "รูปโปรไฟล์",
        updateProfile: "อัปเดตโปรไฟล์",
        updating: "กำลังอัปเดต...",
        profileUpdated: "อัปเดตโปรไฟล์แล้ว",
        profileUpdatedDesc: "อัปเดตโปรไฟล์ของคุณสำเร็จแล้ว",
        imageSelected: "เลือกรูปภาพแล้ว",
        dontForgetSave: "อย่าลืมบันทึกการเปลี่ยนแปลง!",
        confirmResetTitle: "ยืนยันการรีเซ็ต",
        // New notification translations - Thai (avoiding duplicates)
        manageNotifications: "จัดการการแจ้งเตือนของผู้ใช้และประกาศ",
        sendNotification: "ส่งการแจ้งเตือน",
        createAndSend: "สร้างและส่งการแจ้งเตือนให้กับผู้ใช้ที่เลือก",
        notificationTitle: "หัวเรื่องการแจ้งเตือน",
        actionUrlOptional: "URL การดำเนินการ (ไม่บังคับ)",
        notificationMessage: "ข้อความแจ้งเตือน",
        templates: "เทมเพลต (คลิกเพื่อใช้)",
        selectUsers: "เลือกผู้ใช้",
        selected: "เลือกแล้ว",
        sendToUsers: "ส่งให้",
        sending: "กำลังส่ง...",
        userNotifications: "การแจ้งเตือนผู้ใช้",
        viewManageNotifications: "ดูและจัดการการแจ้งเตือนสำหรับผู้ใช้แต่ละคน",
        view: "ดู",
        notificationsFor: "การแจ้งเตือนสำหรับ",
        noNotificationsFound: "ไม่พบการแจ้งเตือน",
        new: "ใหม่",
        action: "การดำเนินการ",
        validationError: "ข้อผิดพลาดการตรวจสอบ",
        fillAllRequiredFields: "กรุณากรอกข้อมูลที่จำเป็นทั้งหมดและเลือกผู้ใช้อย่างน้อยหนึ่งคน",
        notificationSent: "ส่งการแจ้งเตือนให้",
        users: "ผู้ใช้",
        failedToSend: "ไม่สามารถส่งการแจ้งเตือนได้",
        notificationDeleted: "ลบการแจ้งเตือนเรียบร้อยแล้ว",
        totalUsers: "ผู้ใช้ทั้งหมด",
        totalNotifications: "การแจ้งเตือนทั้งหมด",
        unreadNotifications: "ยังไม่ได้อ่าน",
        readNotifications: "อ่านแล้ว",
        allUsers: "ทั้งหมด",
        noUsers: "ไม่มี",
        titleLabel: "หัวเรื่อง",
        typeLabel: "ประเภท",
        messageLabel: "ข้อความ",
        infoType: "ข้อมูล",
        warningType: "คำเตือน",
        successType: "สำเร็จ",
        failedToFetch: "ไม่สามารถดึงข้อมูลผู้ใช้ได้",
        // Barcode Dialog - Thai translations
        addProductsToInventory: "เพิ่มสินค้าเข้าคลังสินค้า",
        scanProductsToSell: "สแกนสินค้าเพื่อขาย",
        barcodeInputLabel: "สแกนหรือใส่บาร์โค้ด",
        barcodeInputPlaceholder: "สแกนหรือใส่บาร์โค้ด",
        productNotFound: "ไม่พบสินค้า",
        pleaseCheckBarcode: "กรุณาตรวจสอบบาร์โค้ด",
        emptyCart: "ตะกร้าว่าง",
        pleaseAddItemsToCart: "กรุณาเพิ่มสินค้าในตะกร้าก่อน",
        productsToAdd: "สินค้าที่จะเพิ่ม",
        itemsToSell: "รายการที่จะขาย",
        itemsCount: "รายการ",
        totalAmount: "รวม",
        onlyQuantityAvailable: "เหลือเพียง",
        quantityAvailable: "ชิ้น",
        addToInventory: "เพิ่มเข้าคลัง",
        confirmSale: "ยืนยันการขาย",
        yourPreferencesSaved: "บันทึกการตั้งค่าของคุณสำเร็จแล้ว",
        // Reports page enhancements
        monthlyPerformance: "ผลงานรายเดือน",
        salesProgress: "ความคืบหน้าการขาย",
        salesTarget: "เป้าหมายการขาย",
        profitTarget: "เป้าหมายกำไร",
        customerSatisfaction: "ความพึงพอใจลูกค้า",
        revenueTrend: "กราฟเเสดงรายได้",
        revenue: "รายได้",
        netProfit: "กำไรสุทธิ",
        salesForecast: "การคาดการณ์การขาย",
        profitForecast: "การคาดการณ์กำไร"
        , loadingChart: "กำลังโหลดกราฟ...",
        loadingCategories: "กำลังโหลดหมวดหมู่...",
        loadingTrend: "กำลังโหลดแนวโน้ม..."
        , noSalesData: "ไม่มีข้อมูลยอดขายสำหรับช่วงที่เลือก",
        noCategoryData: "ไม่มีข้อมูลหมวดหมู่",
        noCategoryContribution: "ไม่มีข้อมูลสัดส่วนหมวดหมู่",
        noStorageLockData: "ไม่มีข้อมูลที่เก็บสินค้า",
        noRevenueTrendData: "ไม่มีข้อมูลแนวโน้มรายได้",
        salesVsCapital: "ยอดขายเทียบทุนสินค้าคงคลัง",
        lowStockCoverage: "สัดส่วนสินค้าใกล้หมด",
        categoryDistribution: "การกระจายหมวดหมู่",
        over: "เกิน",
        more: "เพิ่มเติม",
    }
}