import { clear } from "console";

export const translations = {
    en: {
        error: "Error",
        searchUsers: "Search users...",
        permissionManagement: "Permission Management",
        permissions: "Permissions",
        clear: "Clear",
        loading: "Loading...",
        lotCost: "Lot Cost",
        storageLock: "Storage Lock",
        dashboard: "Dashboard",
        welcome: "Welcome back! Here's what's happening with your inventory.",
        totalProducts: "Total Products",
        todaysSales: "Today's Sales",
        totalProfit: "Total Profit",
        lowStock: "Low Stock Items",
        requiresAttention: "Requires attention",
        salesTrend: "Sales Trend",
        profitTrend: "Profit Trend",
        recentActivity: "Recent Activity",
        // Products
        productManagement: "Product Management",
        manageProducts: "Manage your inventory products and stock levels.",
        addProduct: "Add Product",
        addNewProduct: "Add New Product",
        editProduct: "Edit Product",
        deleteProduct: "Delete Product",
        sellProduct: "Sell Product",
        cancel: "Cancel",
        saveChanges: "Save Changes",
        // Locks
        storageLocks: "Storage Locks",
        manageLocks: "Manage storage locations and capacity.",
        addLock: "Add Storage Lock",
        addNewLock: "Add New Storage Lock",
        editLock: "Edit Storage Lock",
        deleteLock: "Delete Storage Lock",
        lockName: "Lock Name",
        capacity: "Capacity",
        location: "Location",
        // Categories
        categories: "Categories",
        organizeCategories: "Organize your products into categories.",
        addCategory: "Add Category",
        addNewCategory: "Add New Category",
        editCategory: "Edit Category",
        deleteCategory: "Delete Category",
        categoryName: "Category Name",
        description: "Description",
        products: "Products",
        created: "Created",
        actions: "Actions",
        // Sell
        sell: "Sell",
        quantity: "Quantity",
        unitPrice: "Unit Price",
        total: "Total",
        profit: "Profit",
        transactions: "Transactions",
        salesCompletedToday: "Sales completed today",
        // Users
        userManagement: "User Management",
        manageUsers: "Manage users and their permissions.",
        addUser: "Add User",
        addNewUser: "Add New User",
        editUser: "Edit User",
        deleteUser: "Delete User",
        user: "User",
        email: "Email",
        role: "Role",
        status: "Status",
        lastLogin: "Last Login",
        password: "Password",
        // Reports
        reports: "Reports & Analytics",
        trackPerformance: "Track performance and generate insights.",
        exportCSV: "Export CSV",
        exportPDF: "Export PDF",
        reportFilters: "Report Filters",
        dateRange: "Date Range",
        reportType: "Report Type",
        startDate: "Start Date",
        endDate: "End Date",
        totalSales: "Total Sales",
        inventoryValue: "Inventory Value",
        avgOrderValue: "Avg. Order Value",
        salesByCategory: "Category",
        keyMetrics: "Key Metrics",
        bestSellingProduct: "Best Selling Product",
        topCategory: "Top Category",
        avgProfitMargin: "Average Profit Margin",
        totalTransactions: "Total Transactions",
        lowStockItems: "Low Stock Items",
        returnRate: "Return Rate",
        // Common
        update: "Update",
        create: "Create",
        save: "Save",
        search: "Search",
        select: "Select",
        manageInventory: "Manage your inventory products and stock levels.",
        searchProducts: "Search products...",
        product: "Product",
        barcode: "Barcode",
        category: "Category",
        lock: "Storage Lock",
        productName: "Product Name",
        enterProductName: "Enter product name",
        enterBarcode: "Enter barcode",
        scanOrEnterBarcode: "Scan or enter barcode",
        selectCategory: "Select category",
        selectStorageLock: "Select storage lock",
        productImage: "Product Image",
        clickToUpload: "Click or drag to upload",
        imageFormats: "Supported formats: JPG, PNG, GIF",
        uploadingImage: "Uploading image...",
        productAdded: "Product added successfully",
        errorAddingProduct: "Error adding product",
        invalidQuantity: "Invalid quantity",
        available: "Available",
        quantityToSell: "Quantity to Sell",
        max: "Max",
        productInformation: "Product Information",
        categoryStorage: "Category & Storage",
        stockPricing: "Stock & Pricing",
        confirmDelete: "Are you sure you want to delete",
        delete: "Delete",
        customer: "Customer",
        time: "Time",
        searchStorageLocks: "Search storage locks...",
        totalLocks: "Total Locks",
        storageLocations: "Storage locations",
        totalCapacity: "Total Capacity",
        maximumItems: "Maximum items",
        currentStock: "Current Stock",
        itemsStored: "Items stored",
        utilization: "Utilization",
        storageLockUpdated: "Storage lock updated",
        storageLockCreated: "Storage lock created",
        storageLockUpdatedDesc: "The storage lock has been updated successfully.",
        storageLockCreatedDesc: "New storage lock has been created successfully.",
        failedToUpdateStorageLock: "Failed to update storage lock.",
        failedToCreateStorageLock: "Failed to create storage lock.",
        enterLockName: "Enter lock name (e.g., Lock A1)",
        enterMaxCapacity: "Enter maximum capacity",
        enterStorageLocation: "Enter storage location",
        // User-specific translations
        userDeleted: "User deleted",
        userDeletedDesc: "The user has been successfully deleted.",
        failedToDeleteUser: "Failed to delete user.",
        failedToFetchUsers: "Failed to fetch users.",
        userUpdated: "User updated",
        userCreated: "User created",
        userUpdatedDesc: "The user has been successfully updated.",
        userCreatedDesc: "New user has been created successfully.",
        failedToUpdateUser: "Failed to update user.",
        failedToCreateUser: "Failed to create user.",
        selectRole: "Select role",
        selectStatus: "Select status",
        admin: "Admin",
        staff: "Staff",
        viewer: "Viewer",
        active: "Active",
        inactive: "Inactive",
        fullName: "Full Name",
        enterFullName: "Enter full name",
        enterEmail: "Enter email address",
        enterPassword: "Enter password",
        module: "Module",
        configurePermissions: "Configure permissions for different user roles. Changes will apply to all users with the selected role.",
        savePermissions: "Save Permissions",
        fromLastPeriod: "from last period",
        profitMargin: "profit margin",
        currentStockValue: "Current stock value",
        salesProfitTrend: "Sales & Profit Trend",
        inventoryValueTrend: "Inventory Value Trend",
        salesReport: "Sales Report",
        profitAnalysis: "Profit Analysis",
        inventoryReport: "Inventory Report",
        categoryPerformance: "Category Performance",
        last7Days: "Last 7 Days",
        last30Days: "Last 30 Days",
        last3Months: "Last 3 Months",
        last6Months: "Last 6 Months",
        lastYear: "Last Year",
        customRange: "Custom Range",
        sales: "Sales",
        // ...add more as needed
    },
    th: {
        fromLastPeriod: "จากช่วงเวลาก่อนหน้า",
        profitMargin: "อัตรากำไร",
        currentStockValue: "มูลค่าสินค้าคงคลังปัจจุบัน",
        salesProfitTrend: "แนวโน้มยอดขายและกำไร",
        inventoryValueTrend: "แนวโน้มมูลค่าสินค้าคงคลัง",
        salesByCategory: "หมวดหมู่",
        keyMetrics: "ตัวชี้วัดสำคัญ",
        bestSellingProduct: "สินค้าขายดี",
        topCategory: "หมวดหมู่ยอดนิยม",
        avgProfitMargin: "อัตรากำไรเฉลี่ย",
        totalTransactions: "ธุรกรรมทั้งหมด",
        lowStockItems: "สินค้าใกล้หมด",
        returnRate: "อัตราการคืนสินค้า",
        error: "ข้อผิดพลาด",
        searchUsers: "ค้นหาผู้ใช้...",
        permissionManagement: "การจัดการสิทธิ์",
        permissions: "สิทธิ์การเข้าถึง",
        searchStorageLocks: "ค้นหาที่เก็บสินค้า...",
        totalLocks: "จำนวนที่เก็บสินค้าทั้งหมด",
        storageLocations: "ตำแหน่งที่เก็บสินค้า",
        totalCapacity: "ความจุรวม",
        maximumItems: "จำนวนสูงสุด",
        currentStock: "สต็อกปัจจุบัน",
        itemsStored: "จำนวนที่จัดเก็บ",
        utilization: "การใช้งาน",
        storageLockUpdated: "อัปเดตที่เก็บสินค้าแล้ว",
        storageLockCreated: "สร้างที่เก็บสินค้าแล้ว",
        storageLockUpdatedDesc: "อัปเดตที่เก็บสินค้าสำเร็จ",
        storageLockCreatedDesc: "สร้างที่เก็บสินค้าใหม่สำเร็จ",
        failedToUpdateStorageLock: "อัปเดตที่เก็บสินค้าไม่สำเร็จ",
        failedToCreateStorageLock: "สร้างที่เก็บสินค้าไม่สำเร็จ",
        enterLockName: "กรอกชื่อที่เก็บ (เช่น Lock A1)",
        enterMaxCapacity: "กรอกความจุสูงสุด",
        enterStorageLocation: "กรอกตำแหน่งที่เก็บสินค้า",
        clear: "ล้าง",
        time: "เวลา",
        customer: "ลูกค้า",
        loading: "กำลังโหลด...",
        lotCost: "ต้นทุนล็อต",
        storageLock: "ล็อคที่เก็บสินค้า",
        dashboard: "แดชบอร์ด",
        welcome: "ยินดีต้อนรับ! นี่คือภาพรวมสินค้าคงคลังของคุณ",
        totalProducts: "สินค้าทั้งหมด",
        todaysSales: "ยอดขายวันนี้",
        totalProfit: "กำไรรวม",
        lowStock: "สินค้าใกล้หมด",
        requiresAttention: "ต้องการตรวจสอบ",
        salesTrend: "แนวโน้มยอดขาย",
        profitTrend: "แนวโน้มกำไร",
        recentActivity: "กิจกรรมล่าสุด",
        // Products
        productManagement: "จัดการสินค้า",
        manageProducts: "จัดการสินค้าและสต็อกของคุณ",
        addProduct: "เพิ่มสินค้า",
        addNewProduct: "เพิ่มสินค้าใหม่",
        editProduct: "แก้ไขสินค้า",
        deleteProduct: "ลบสินค้า",
        sellProduct: "ขายสินค้า",
        cancel: "ยกเลิก",
        saveChanges: "บันทึกการเปลี่ยนแปลง",
        // Locks
        storageLocks: "ที่เก็บสินค้า",
        manageLocks: "จัดการที่เก็บสินค้าและความจุ",
        addLock: "เพิ่มที่เก็บสินค้า",
        addNewLock: "เพิ่มที่เก็บสินค้าใหม่",
        editLock: "แก้ไขที่เก็บสินค้า",
        deleteLock: "ลบที่เก็บสินค้า",
        lockName: "ชื่อที่เก็บ",
        capacity: "ความจุ",
        location: "ตำแหน่ง",
        // Categories
        categories: "หมวดหมู่",
        organizeCategories: "จัดหมวดหมู่สินค้า",
        addCategory: "เพิ่มหมวดหมู่",
        addNewCategory: "เพิ่มหมวดหมู่ใหม่",
        editCategory: "แก้ไขหมวดหมู่",
        deleteCategory: "ลบหมวดหมู่",
        categoryName: "ชื่อหมวดหมู่",
        description: "รายละเอียด",
        products: "สินค้า",
        created: "สร้างเมื่อ",
        actions: "การกระทำ",
        // Sell
        sell: "ขาย",
        quantity: "จำนวน",
        unitPrice: "ราคาต่อหน่วย",
        total: "รวม",
        profit: "กำไร",
        transactions: "ธุรกรรม",
        salesCompletedToday: "ขายสำเร็จวันนี้",
        // Users
        userManagement: "จัดการผู้ใช้",
        manageUsers: "จัดการผู้ใช้และสิทธิ์การเข้าถึง",
        addUser: "เพิ่มผู้ใช้",
        addNewUser: "เพิ่มผู้ใช้ใหม่",
        editUser: "แก้ไขผู้ใช้",
        deleteUser: "ลบผู้ใช้",
        user: "ผู้ใช้",
        email: "อีเมล",
        role: "บทบาท",
        status: "สถานะ",
        lastLogin: "เข้าสู่ระบบล่าสุด",
        password: "รหัสผ่าน",
        // Reports
        reports: "รายงานและวิเคราะห์",
        trackPerformance: "ติดตามผลและวิเคราะห์ข้อมูล",
        exportCSV: "ส่งออก CSV",
        exportPDF: "ส่งออก PDF",
        reportFilters: "ตัวกรองรายงาน",
        dateRange: "ช่วงวันที่",
        reportType: "ประเภทรายงาน",
        startDate: "วันที่เริ่มต้น",
        endDate: "วันที่สิ้นสุด",
        totalSales: "ยอดขายรวม",
        inventoryValue: "มูลค่าสินค้าคงคลัง",
        avgOrderValue: "มูลค่าคำสั่งซื้อเฉลี่ย",
        // Common
        update: "อัปเดต",
        create: "สร้าง",
        save: "บันทึก",
        search: "ค้นหา",
        select: "เลือก",
        // Add these for product page and dialogs:
        manageInventory: "จัดการสินค้าและสต็อกของคุณ",
        searchProducts: "ค้นหาสินค้า...",
        product: "สินค้า",
        barcode: "บาร์โค้ด",
        category: "หมวดหมู่",
        lock: "ที่เก็บสินค้า",
        productName: "ชื่อสินค้า",
        enterProductName: "กรอกชื่อสินค้า",
        enterBarcode: "กรอกบาร์โค้ด",
        scanOrEnterBarcode: "สแกนหรือกรอกบาร์โค้ด",
        selectCategory: "เลือกหมวดหมู่",
        selectStorageLock: "เลือกที่เก็บสินค้า",
        productImage: "รูปสินค้า",
        clickToUpload: "คลิกหรือวางไฟล์เพื่ออัปโหลด",
        imageFormats: "รองรับไฟล์: JPG, PNG, GIF",
        uploadingImage: "กำลังอัปโหลดรูปภาพ...",
        productAdded: "เพิ่มสินค้าสำเร็จ",
        errorAddingProduct: "เกิดข้อผิดพลาดในการเพิ่มสินค้า",
        invalidQuantity: "จำนวนไม่ถูกต้อง",
        available: "คงเหลือ",
        quantityToSell: "จำนวนที่ต้องการขาย",
        max: "สูงสุด",
        productInformation: "ข้อมูลสินค้า",
        categoryStorage: "หมวดหมู่และที่เก็บ",
        stockPricing: "สต็อกและราคา",
        confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบ",
        delete: "ลบ",
        // User-specific translations
        userDeleted: "ลบผู้ใช้แล้ว",
        userDeletedDesc: "ลบผู้ใช้สำเร็จ",
        failedToDeleteUser: "ลบผู้ใช้ไม่สำเร็จ",
        failedToFetchUsers: "ดึงข้อมูลผู้ใช้ไม่สำเร็จ",
        userUpdated: "อัปเดตผู้ใช้แล้ว",
        userCreated: "สร้างผู้ใช้แล้ว",
        userUpdatedDesc: "อัปเดตผู้ใช้สำเร็จ",
        userCreatedDesc: "สร้างผู้ใช้ใหม่สำเร็จ",
        failedToUpdateUser: "อัปเดตผู้ใช้ไม่สำเร็จ",
        failedToCreateUser: "สร้างผู้ใช้ไม่สำเร็จ",
        selectRole: "เลือกบทบาท",
        selectStatus: "เลือกสถานะ",
        admin: "ผู้ดูแล",
        staff: "พนักงาน",
        viewer: "ผู้ชม",
        active: "ใช้งาน",
        inactive: "ไม่ใช้งาน",
        fullName: "ชื่อ-นามสกุล",
        enterFullName: "กรอกชื่อ-นามสกุล",
        enterEmail: "กรอกอีเมล",
        enterPassword: "กรอกรหัสผ่าน",
        module: "โมดูล",
        configurePermissions: "กำหนดสิทธิ์สำหรับบทบาทผู้ใช้แต่ละประเภท การเปลี่ยนแปลงจะมีผลกับผู้ใช้ทุกคนในบทบาทที่เลือก",
        savePermissions: "บันทึกสิทธิ์",
        read: "อ่าน",
        last7Days: "7 วันที่ผ่านมา",
        last30Days: "30 วันที่ผ่านมา",
        last3Months: "3 เดือนที่ผ่านมา",
        last6Months: "6 เดือนที่ผ่านมา",
        lastYear: "ปีที่ผ่านมา",
        customRange: "กำหนดช่วงเอง",
        salesReport: "รายงานยอดขาย",
        profitAnalysis: "วิเคราะห์กำไร",
        inventoryReport: "รายงานสินค้าคงคลัง",
        categoryPerformance: "ประสิทธิภาพหมวดหมู่",
        sales: "ยอดขาย",
    }
}